services:
  app:
    image: socketoi-dev
    build:
      context: .
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
